version: "3"
services:
  registry:
    image: jhipster/jhipster-registry:v3.2.4
    volumes:
      - ./registry:/central-config
    # When run with the "dev" Spring profile, the JHipster Registry will
    # read the config from the local filesystem (central-server-config directory)
    # When run with the "prod" Spring profile, it will read the configuration from a Git repository
    # See http://www.jhipster.tech/microservices-architecture/#registry_app_configuration
    environment:
      - SPRING_PROFILES_ACTIVE=dev,native,swagger
      - SECURITY_USER_PASSWORD=admin
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/
      # - GIT_URI=https://github.com/jhipster/jhipster-registry/
      # - GIT_SEARCH_PATHS=central-config
    ports:
      - 8761:8761
  mongo:
    image: mongo:3.4.10
    ports:
      - 27017:27017

  postgres:
    image: postgres:9.6.5
      # volumes:
      #     - ~/volumes/jhipster/jobs/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jobs
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
  jaegger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp 
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411

  #########################
  # Sentry.io config
  #########################
  sentry-redis:
    image: redis
  sentry-postgres:
    image: postgres
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
      POSTGRES_DB: sentry

  sentry:
    image: sentry
    links:
    - sentry-redis
    - sentry-postgres
    ports:
    - 9000:9000
    environment:
      SENTRY_SECRET_KEY: '6e261ca6e11c45849d961792749f7c6d'
      SENTRY_POSTGRES_HOST: sentry-postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: sentry-redis

  cron:
    image: sentry
    links:
    - sentry-redis
    - sentry-postgres
    command: "sentry run cron"
    environment:
      SENTRY_SECRET_KEY: '6e261ca6e11c45849d961792749f7c6d'
      SENTRY_POSTGRES_HOST: sentry-postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: sentry-redis

  worker:
    image: sentry
    links:
    - sentry-redis
    - sentry-postgres
    command: "sentry run worker"
    environment:
      SENTRY_SECRET_KEY: '6e261ca6e11c45849d961792749f7c6d'
      SENTRY_POSTGRES_HOST: sentry-postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: sentry-redis

  #########################
  # Graphite & Grafana
  #########################
  graphite:
    image: hopsoft/graphite-statsd
    ports:
      - 9091:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    links:
      - graphite
