version: '2'
services:
    jobs-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/jobs/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jobs
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
